services:
  php:
    image: ghcr.io/eventpoints/guessthedailyword.com-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: 50s
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      MERCURE_PUBLIC_URL: "https://guessthedailyword.com/.well-known/mercure"
      DATABASE_URL: "postgresql://__GUESS_THE_DAILY_POSTGRES_USER__:__GUESS_THE_DAILY_POSTGRES_PASSWORD__@database:5432/__GUESS_THE_DAILY_POSTGRES_DBNAME__?serverVersion=17&charset=utf8"
      MERCURE_JWT_SECRET: "__GUESS_THE_DAILY_WORD__MERCURE_JWT_SECRET__"
      APP_SECRET: "__GUESS_THE_DAILY_APP_SECRET__"
      MAILER_DSN: "__GUESS_THE_DAILY_MAILER_DSN__"
      MESSENGER_TRANSPORT_DSN: "__GUESS_THE_DAILY_MESSENGER_TRANSPORT_DSN__"
      APP_TIMEZONE: "__GUESS_THE_DAILY_APP_TIMEZONE__"
      CORS_ALLOW_ORIGIN: "__GUESS_THE_DAILY_CORS_ALLOW_ORIGIN__"
      JWT_SECRET_KEY: __GUESS_THE_DAILY_JWT_SECRET_KEY__
      JWT_PUBLIC_KEY: __GUESS_THE_DAILY_JWT_PUBLIC_KEY__
      JWT_PASSPHRASE: __GUESS_THE_DAILY_JWT_PASSPHRASE__
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/guessthedailyword.com-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "__GUESS_THE_DAILY_MERCURE_JWT_SECRET__"
      MERCURE_SUBSCRIBER_JWT_KEY: "__GUESS_THE_DAILY_MERCURE_JWT_SECRET__"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guessthedailyword.rule=Host(`guessthedailyword.com`, `www.guessthedailyword.com`)"
      - "traefik.http.routers.guessthedailyword.tls=true"
      - "traefik.http.routers.guessthedailyword.tls.certresolver=le"
    networks:
      - traefik
      - internal

  database:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__GUESS_THE_DAILY_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__GUESS_THE_DAILY_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__GUESS_THE_DAILY_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guessthedailyword-adminer.rule=Host(`adminer.guessthedailyword.com`)"
      - "traefik.http.routers.guessthedailyword-adminer.tls=true"
      - "traefik.http.routers.guessthedailyword-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik

networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config: